### ISSUE TITLE
Assignment4+Assignment5

### ISSUE THREAD

**Issue by vkats-spbu** [Begaliev-Kirill/HomeAssignments#4]
В Makefile некоректно заданы опции компилятора (CCXFLAGS вместо CXXFLAGS). Исправьте.

**Comment by Begaliev-Kirill** [comment]
Исправил

**Comment by vkats-spbu** [comment]
Теперь сборка завершается с ошибками:

4 задание:
<pre>victor@victor-VirtualBox:~/accesment/Begaliev-Kirill/HomeAssignments/Assignment4$ make
g++ -I. -std=c++17 -Werror -Wpedantic -Wall -g -fPIC   -c -o main.o main.cpp
g++ -I. -std=c++17 -Werror -Wpedantic -Wall -g -fPIC   -c -o Transformer.o Transformer.cpp
g++ -I. -std=c++17 -Werror -Wpedantic -Wall -g -fPIC   -c -o Weapon.o Weapon.cpp
g++ -I. -std=c++17 -Werror -Wpedantic -Wall -g -fPIC   -c -o Communicate_module.o Communicate_module.cpp
g++ -I. -std=c++17 -Werror -Wpedantic -Wall -g -fPIC   -c -o Zoomorph.o Zoomorph.cpp
In file included from <b>Zoomorph.cpp:6</b>:
<b>Zoomorph.hpp:19:25:</b> <font color="#C01C28"><b>error: </b></font>extra ‘<b>;</b>’ [<font color="#C01C28"><b>-Werror=pedantic</b></font>]
   19 |     bool is_imitating();<font color="#C01C28"><b>;</b></font>
      |                         <font color="#C01C28"><b>^</b></font>
      |                         <font color="#C01C28">-</font>
cc1plus: all warnings being treated as errors
make: *** [&lt;builtin&gt;: Zoomorph.o] Error 1
</pre>

5 задание:

<pre>victor@victor-VirtualBox:~/accesment/Begaliev-Kirill/HomeAssignments/Assignment5$ make
g++ -I. -std=c++17 -Werror -Wpedantic -Wall -g -fPIC   -c -o main.o main.cpp
g++ -I. -std=c++17 -Werror -Wpedantic -Wall -g -fPIC   -c -o Transformer.o Transformer.cpp
g++ -I. -std=c++17 -Werror -Wpedantic -Wall -g -fPIC   -c -o Weapon.o Weapon.cpp
g++ -I. -std=c++17 -Werror -Wpedantic -Wall -g -fPIC   -c -o Communicate_module.o Communicate_module.cpp
g++ -I. -std=c++17 -Werror -Wpedantic -Wall -g -fPIC   -c -o Zoomorph.o Zoomorph.cpp
In file included from <b>Zoomorph.cpp:6</b>:
<b>Zoomorph.hpp:19:25:</b> <font color="#C01C28"><b>error: </b></font>extra ‘<b>;</b>’ [<font color="#C01C28"><b>-Werror=pedantic</b></font>]
   19 |     bool is_imitating();<font color="#C01C28"><b>;</b></font>
      |                         <font color="#C01C28"><b>^</b></font>
      |                         <font color="#C01C28">-</font>
cc1plus: all warnings being treated as errors
make: *** [&lt;builtin&gt;: Zoomorph.o] Error 1
</pre>

**Comment by Begaliev-Kirill** [comment]
Исправил, компиляция и тесты проходят без ошибок

**Comment by MarryAnt** [comment]
Assignment 5. По условию задания необходимо:
1) Протестировать используемые методы **явно**
2) Протестировать вызов методов из **указателя, типизированного предком**
3) Протестировать **в цикле** - _выполнено_

**Comment by Begaliev-Kirill** [comment]
Добавил явное использование, но тесты Desipticon и Autobot в цикле проходили с указателем, типизированным Transformer, вынес тесты Assignment5 в отдельный файл
